name: IWD CI

description: Runs IWD's CI

inputs:
  github_token:
    required: true
  email_token:
    required: true
  patchwork_token:
    required: true

runs:
  using: 'composite'
  steps:
    - name: Docker
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        EMAIL_TOKEN: ${{ inputs.email_token }}
        PATCHWORK_TOKEN : ${{ inputs.patchwork_token }}
      run: |
        export
        /usr/bin/docker build -t $GITHUB_RUN_ID -f "$GITHUB_ACTION_PATH/Dockerfile" "$GITHUB_ACTION_PATH"
        /usr/bin/docker run --privileged --workdir /github/workspace --rm \
              -e GITHUB_TOKEN -e EMAIL_TOKEN -e PATCHWORK_TOKEN -e HOME -e GITHUB_REF -e GITHUB_REPOSITORY \
              -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_WORKFLOW \
              -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_REF_NAME -e GITHUB_ACTOR \
              -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_PATH -e GITHUB_JOB \
              -e GITHUB_ENV -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE \
              -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN \
              -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true \
              -v "/var/run/docker.sock":"/var/run/docker.sock" \
              -v "/home/runner/work/_temp/_github_home":"/github/home" \
              -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" \
              -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" \
              -v "$GITHUB_WORKSPACE":"$GITHUB_WORKSPACE" \
              -v "/home/runner":"/home/runner" $GITHUB_RUN_ID
